controller_list:
 - name: arm1_controller
   action_ns: "follow_joint_trajectory"
   type: FollowJointTrajectory
   joints: [arm1_to_arm2, arm2_to_arm3, arm3_to_arm4, arm4_to_arm5, arm5_to_arm6, arm6_to_arm7, arm7_to_arm8]
