controller_list:
  - name: fake_arm_controller
    joints:
      - arm1_to_arm2
      - arm2_to_arm3
      - arm3_to_arm4
      - arm4_to_arm5
      - arm5_to_arm6
      - arm6_to_arm7
      - arm7_to_arm8
  - name: fake_gripper_controller
    joints:
      - gripper