controller_list:
  - name: fake_right_arm_controller
    joints:
      - JointRightShoulderPan
      - JointRightShoulderTilt
      - JointRightUpperArmRoll
      - JointRightElbowFlex
      - JointRightForearmRoll
      - JointRightWristFlex
      - JointRightWristRoll
  - name: fake_left_arm_controller
    joints:
      - JointRightShoulderPan
      - JointRightShoulderTilt
      - JointRightUpperArmRoll
      - JointRightElbowFlex
      - JointRightForearmRoll
      - JointRightWristFlex
      - JointRightWristRoll
  - name: fake_right_gripper_controller
    joints:
      - JointRightGripper
  - name: fake_left_gripper_controller
    joints:
      - JointLeftGripper
