# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  JointLeftElbowFlex:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointLeftForearmRoll:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointLeftGripper:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointLeftShoulderPan:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointLeftShoulderTilt:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointLeftUpperArmRoll:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointLeftWristFlex:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointLeftWristRoll:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointRightElbowFlex:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  JointRightForearmRoll:
    has_velocity_limits: true
    max_velocity: 1.4661
    has_acceleration_limits: false
    max_acceleration: 0
  JointRightGripper:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  JointRightShoulderPan:
    has_velocity_limits: true
    max_velocity: 0.2932
    has_acceleration_limits: false
    max_acceleration: 0
  JointRightShoulderTilt:
    has_velocity_limits: true
    max_velocity: 0.075
    has_acceleration_limits: false
    max_acceleration: 0
  JointRightUpperArmRoll:
    has_velocity_limits: true
    max_velocity: 0.25
    has_acceleration_limits: false
    max_acceleration: 0
  JointRightWristFlex:
    has_velocity_limits: true
    max_velocity: 0.733
    has_acceleration_limits: false
    max_acceleration: 0
  JointRightWristRoll:
    has_velocity_limits: true
    max_velocity: 7.5398
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper1_to_left_gripper3:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper1_to_left_gripper4l:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper1_to_left_gripper4r:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper2_to_left_gripper6:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper3_to_left_gripper5:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper1_to_right_gripper3:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper1_to_right_gripper4l:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper1_to_right_gripper4r:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper2_to_right_gripper6:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper3_to_right_gripper5:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0